{
  "hash": "a26a2c59f8a1f30cde4dd061e31f540c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Lecture 14: Futures, Hedging, and Basis Risk\"\ndescription: \"NREC4230 Agricultural Finance lecture note on spot markets, futures markets, hedging, basis risk, partial hedging, and agricultural price-risk management.\"\n---\n\n## Learning objectives\n\nBy the end of this lecture, students should be able to:\n\n1. Explain the difference between spot, forward, and futures markets.\n2. Describe how farmers use short futures positions to hedge price risk.\n3. Calculate revenues with and without a futures hedge.\n4. Explain basis and basis risk.\n5. Compare full hedging with partial hedging.\n6. Calculate an optimal hedge ratio and the number of futures contracts.\n7. Interpret futures hedging as a risk-management tool, not as a guaranteed profit strategy.\n\n---\n\n## 1. Why futures markets matter in agricultural finance\n\nFarmers usually make production decisions before they know the final selling price. A wheat, maize, dairy, date, or tomato producer may invest in land preparation, labour, irrigation, feed, fertilizer, storage, and transport months before harvest or sale. If prices fall before the product is sold, the farmer's revenue can decline sharply.\n\nFutures markets help manage this price risk. A futures contract allows a producer, trader, processor, or investor to lock in or hedge a future price exposure. In agricultural finance, futures markets are important because they connect:\n\n- production decisions\n- cash-flow planning\n- credit repayment capacity\n- risk management\n- food-system price expectations\n\n::: {.callout-note}\n## Key idea\nA hedge is not mainly designed to maximize profit. It is designed to reduce uncertainty about future revenue or future cost.\n:::\n\n---\n\n## 2. Spot, forward, and futures markets\n\n### Spot market\n\nA **spot market** is a market for immediate purchase or sale. The price is the current market price.\n\nExample: A farmer sells 20 tons of wheat today at OMR 115 per ton.\n\n### Forward contract\n\nA **forward contract** is a private agreement between two parties to buy or sell a commodity at a future date for a price agreed today.\n\nExample: A farmer agrees with a miller to sell 20 tons of wheat in three months at OMR 120 per ton.\n\n### Futures contract\n\nA **futures contract** is a standardized contract traded on an organized exchange. It specifies the commodity, contract size, maturity month, and other delivery terms.\n\nExample: A wheat futures contract may represent a standardized amount of wheat for delivery or settlement in a future month.\n\n| Feature | Forward contract | Futures contract |\n|---|---|---|\n| Trading place | Private agreement | Organized exchange |\n| Standardization | Customized | Standardized |\n| Counterparty risk | Higher | Lower due to clearinghouse |\n| Liquidity | Often lower | Usually higher |\n| Daily settlement | Usually no | Yes, marked to market |\n| Flexibility | High | Lower |\n| Transparency | Lower | Higher |\n\n---\n\n## 3. Hedging logic for farmers\n\nA farmer is naturally **long** the physical commodity because the farmer will own the crop at harvest. If the price falls, the farmer loses revenue.\n\nTo reduce this risk, the farmer can take a **short futures position**.\n\n- The farmer sells futures today.\n- If the future price falls, the short futures position gains.\n- This gain partly or fully offsets the lower spot-market revenue.\n\n### Short hedge\n\nA **short hedge** is used by producers who plan to sell a commodity in the future.\n\n$$\n\\text{Futures Gain for Short Hedge} = (F_0 - F_T) \\times Q_h\n$$\n\nwhere:\n\n- $F_0$ is the initial futures price\n- $F_T$ is the futures price when the hedge is closed\n- $Q_h$ is the hedged quantity\n\nIf $F_T < F_0$, the short hedge gains.\n\nIf $F_T > F_0$, the short hedge loses.\n\n::: {.callout-tip}\n## Producer rule\nA farmer worried about falling prices uses a short hedge. A buyer worried about rising prices uses a long hedge.\n:::\n\n---\n\n## 4. No hedge versus full hedge\n\nAssume a wheat farmer expects to harvest 200 tons in three months.\n\n| Variable | Value |\n|---|---:|\n| Expected output | 200 tons |\n| Current spot price | OMR 123 per ton |\n| Three-month futures price | OMR 125 per ton |\n| Harvest spot price | OMR 105 per ton |\n| Harvest futures price | OMR 110 per ton |\n| Contract size | 10 tons |\n\n### No hedging\n\nIf the farmer does not hedge, revenue depends only on the harvest spot price.\n\n$$\n\\text{Revenue without hedge} = Q \\times S_T\n$$\n\n$$\n= 200 \\times 105 = 21{,}000\n$$\n\nThe farmer receives OMR 21,000.\n\n### Full hedge\n\nA full hedge covers the entire expected output.\n\n$$\n\\text{Number of contracts} = \\frac{Q}{\\text{Contract size}}\n$$\n\n$$\n= \\frac{200}{10} = 20\n$$\n\nThe farmer sells 20 futures contracts.\n\nRevenue from selling wheat in the spot market:\n\n$$\n200 \\times 105 = 21{,}000\n$$\n\nFutures gain:\n\n$$\n(F_0 - F_T) \\times Q = (125 - 110) \\times 200 = 3{,}000\n$$\n\nTotal revenue after hedge:\n\n$$\n21{,}000 + 3{,}000 = 24{,}000\n$$\n\nThe hedge improves realized revenue from OMR 21,000 to OMR 24,000.\n\n::: {.callout-note}\n## Interpretation\nThe spot price fell, which hurt the farmer. The futures price also fell, which created a gain on the short futures position.\n:::\n\n---\n\n## 5. If prices rise instead\n\nHedging protects against downside risk, but it can also reduce the benefit from favorable price movements.\n\nSuppose the same farmer hedges at OMR 125 per ton, but at harvest:\n\n| Variable | Value |\n|---|---:|\n| Harvest spot price | OMR 135 per ton |\n| Harvest futures price | OMR 138 per ton |\n\nSpot revenue:\n\n$$\n200 \\times 135 = 27{,}000\n$$\n\nFutures gain or loss:\n\n$$\n(125 - 138) \\times 200 = -2{,}600\n$$\n\nTotal revenue after hedge:\n\n$$\n27{,}000 - 2{,}600 = 24{,}400\n$$\n\nThe farmer still earns more than in the low-price case, but less than the unhedged revenue of OMR 27,000.\n\n::: {.callout-warning}\n## Common mistake\nStudents often say that hedging is always profitable. This is incorrect. Hedging reduces price risk, but it can also reduce upside gains when prices move favorably.\n:::\n\n---\n\n## 6. Basis and basis risk\n\nThe **basis** is the difference between the spot price and the futures price.\n\n$$\n\\text{Basis} = S - F\n$$\n\nwhere:\n\n- $S$ is the spot price\n- $F$ is the futures price\n\nBasis matters because spot and futures prices do not always move perfectly together.\n\n### Basis at time 0\n\n$$\nB_0 = S_0 - F_0\n$$\n\nUsing the earlier example:\n\n$$\nB_0 = 123 - 125 = -2\n$$\n\n### Basis at harvest\n\n$$\nB_T = S_T - F_T\n$$\n\n$$\nB_T = 105 - 110 = -5\n$$\n\nThe basis changed from $-2$ to $-5$.\n\n### Why basis risk matters\n\nUnder a full hedge, the farmer's effective price is:\n\n$$\n\\text{Effective Price} = S_T + (F_0 - F_T)\n$$\n\nThis can be rearranged as:\n\n$$\n\\text{Effective Price} = F_0 + B_T\n$$\n\nSo the final hedged price depends on the initial futures price and the final basis.\n\nIf the final basis is not known with certainty, the hedge is not perfect.\n\n::: {.callout-important}\n## Key idea\nFutures hedging removes much of the price-level risk, but it does not remove basis risk.\n:::\n\n---\n\n## 7. Worked example: basis risk\n\nA barley farmer hedges 100 tons.\n\n| Variable | Value |\n|---|---:|\n| Initial spot price, $S_0$ | OMR 118 per ton |\n| Initial futures price, $F_0$ | OMR 120 per ton |\n| Harvest spot price, $S_T$ | OMR 112 per ton |\n| Harvest futures price, $F_T$ | OMR 113 per ton |\n\nBasis at time 0:\n\n$$\nB_0 = 118 - 120 = -2\n$$\n\nBasis at harvest:\n\n$$\nB_T = 112 - 113 = -1\n$$\n\nThe basis strengthened from $-2$ to $-1$.\n\nSpot revenue:\n\n$$\n112 \\times 100 = 11{,}200\n$$\n\nFutures gain:\n\n$$\n(120 - 113) \\times 100 = 700\n$$\n\nTotal hedged revenue:\n\n$$\n11{,}200 + 700 = 11{,}900\n$$\n\nEffective price:\n\n$$\n\\frac{11{,}900}{100} = 119\n$$\n\nThe farmer did not lock in exactly OMR 120. The realized effective price was OMR 119 because the final basis was $-1$.\n\n---\n\n## 8. Partial hedging\n\nA full hedge covers all expected output. A partial hedge covers only part of expected output.\n\nA farmer may use partial hedging because:\n\n- output quantity is uncertain\n- futures contract sizes do not match production exactly\n- the farmer wants some upside if prices rise\n- the farmer does not want to post too much margin\n- basis risk is high\n- liquidity is limited\n\n### Example: 80% hedge\n\nA cacao farmer expects to harvest 5,000 kg. The farmer hedges 80% using short futures at OMR 8.7 per kg.\n\n| Variable | Value |\n|---|---:|\n| Expected harvest | 5,000 kg |\n| Hedge ratio | 80% |\n| Hedged quantity | 4,000 kg |\n| Futures price today | OMR 8.7 per kg |\n\n#### Case A: price falls\n\nAt harvest, spot price is OMR 5.5 per kg.\n\nSpot revenue:\n\n$$\n5{,}000 \\times 5.5 = 27{,}500\n$$\n\nFutures gain:\n\n$$\n(8.7 - 5.5) \\times 4{,}000 = 12{,}800\n$$\n\nTotal revenue:\n\n$$\n27{,}500 + 12{,}800 = 40{,}300\n$$\n\n#### Case B: price rises\n\nAt harvest, spot price is OMR 10.0 per kg.\n\nSpot revenue:\n\n$$\n5{,}000 \\times 10.0 = 50{,}000\n$$\n\nFutures loss:\n\n$$\n(8.7 - 10.0) \\times 4{,}000 = -5{,}200\n$$\n\nTotal revenue:\n\n$$\n50{,}000 - 5{,}200 = 44{,}800\n$$\n\n::: {.callout-note}\n## Interpretation\nPartial hedging protects most of the farmer's income when prices fall, but still allows some benefit from price increases on the unhedged quantity.\n:::\n\n---\n\n## 9. Optimal hedge ratio\n\nA hedge ratio tells us what share of the physical exposure should be hedged.\n\nA simple full hedge ratio is:\n\n$$\nh = 1\n$$\n\nA partial hedge might use:\n\n$$\nh = 0.50, 0.70, \\text{or } 0.80\n$$\n\nIn a more formal risk-minimization setting, the optimal hedge ratio is:\n\n$$\nh^* = \\rho_{SF} \\frac{\\sigma_S}{\\sigma_F}\n$$\n\nwhere:\n\n- $\\rho_{SF}$ is the correlation between spot price changes and futures price changes\n- $\\sigma_S$ is the standard deviation of spot price changes\n- $\\sigma_F$ is the standard deviation of futures price changes\n\n### Example\n\nAssume:\n\n| Variable | Value |\n|---|---:|\n| Correlation between spot and futures price changes | 0.90 |\n| Standard deviation of spot price changes | 12 |\n| Standard deviation of futures price changes | 10 |\n\nThen:\n\n$$\nh^* = 0.90 \\times \\frac{12}{10} = 1.08\n$$\n\nThis means the minimum-variance hedge is 108% of the physical exposure. In practice, a farmer may round down to avoid over-hedging, especially if output quantity is uncertain.\n\n### Number of contracts\n\n$$\nN^* = \\frac{h^* Q}{\\text{Contract Size}}\n$$\n\nIf $Q = 200$ tons and contract size is 10 tons:\n\n$$\nN^* = \\frac{1.08 \\times 200}{10} = 21.6\n$$\n\nThe farmer may use 21 or 22 contracts, depending on risk tolerance and policy.\n\n---\n\n## 10. Python example\n\nThe following code calculates hedged revenue, basis, and contract numbers.\n\n::: {#futures-hedge-example .cell execution_count=1}\n``` {.python .cell-code}\nQ = 200\ncontract_size = 10\n\nS0 = 123\nF0 = 125\nST = 105\nFT = 110\n\ncontracts = Q / contract_size\nspot_revenue = Q * ST\nfutures_gain = (F0 - FT) * Q\nhedged_revenue = spot_revenue + futures_gain\n\nbasis_0 = S0 - F0\nbasis_T = ST - FT\neffective_price = hedged_revenue / Q\n\nprint(\"Contracts:\", contracts)\nprint(\"Spot revenue:\", spot_revenue)\nprint(\"Futures gain:\", futures_gain)\nprint(\"Hedged revenue:\", hedged_revenue)\nprint(\"Basis at time 0:\", basis_0)\nprint(\"Basis at harvest:\", basis_T)\nprint(\"Effective price:\", effective_price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nContracts: 20.0\nSpot revenue: 21000\nFutures gain: 3000\nHedged revenue: 24000\nBasis at time 0: -2\nBasis at harvest: -5\nEffective price: 120.0\n```\n:::\n:::\n\n\n---\n\n## 11. Futures versus speculation\n\nHedging and speculation are different.\n\n| Activity | Main purpose | Example |\n|---|---|---|\n| Hedging | Reduce an existing risk | Farmer shorts futures to protect crop price |\n| Speculation | Take risk to earn profit | Trader buys futures expecting prices to rise |\n| Arbitrage | Exploit price mispricing | Trader buys cheap contract and sells expensive equivalent |\n\nFarmers may use futures markets as hedgers. They already face price risk from production. The futures position is used to offset that existing exposure.\n\n::: {.callout-warning}\n## Common mistake\nA farmer who shorts futures to protect a crop is not simply \"betting against the market.\" The farmer is reducing an existing exposure.\n:::\n\n---\n\n## 12. Spread trading\n\nA spread trade involves buying one futures contract and selling another related futures contract. Spread trades are common in commodity markets.\n\nExample:\n\n- Buy May wheat futures\n- Sell July wheat futures\n\nThe trader is not mainly betting on the absolute wheat price. The trader is betting on the price difference between two contracts.\n\n### Simple spread example\n\n| Contract | Initial action | Initial price | Closing price | Profit or loss |\n|---|---|---:|---:|---:|\n| May contract | Buy | 1140 | 1155 | +15 |\n| July contract | Sell | 1160 | 1165 | -5 |\n\nNet profit:\n\n$$\n15 - 5 = 10\n$$\n\nSpread trading is usually more relevant for traders than small farmers, but it helps students understand how futures prices across maturities are linked.\n\n---\n\n## 13. Oman applications\n\nOman does not have a deep domestic agricultural futures market for most local products. However, futures-market logic is still useful for agricultural finance in Oman because:\n\n- imported wheat, maize, soybean meal, sugar, and edible oils are linked to global commodity prices\n- livestock and poultry feed costs are affected by international grain and oilseed markets\n- food importers face exchange-rate and commodity-price risk\n- farm investment decisions depend on expected future prices\n- banks need to understand borrower exposure to input and output price volatility\n\n### Example: feed cost risk\n\nA dairy farm in Oman may not trade futures directly, but its feed supplier may face global maize and soybean meal price risk. If feed prices rise, the farm's operating cost increases and loan repayment capacity weakens.\n\n### Example: wheat import risk\n\nA food importer may use international futures or forward contracts to reduce the cost uncertainty of future wheat purchases.\n\n---\n\n## 14. Common mistakes\n\n::: {.callout-warning}\n## Mistake 1: Confusing spot and futures prices\nThe spot price is for immediate transaction. The futures price is for a future contract.\n:::\n\n::: {.callout-warning}\n## Mistake 2: Using a long hedge for a producer\nA producer who will sell output later usually uses a short hedge, not a long hedge.\n:::\n\n::: {.callout-warning}\n## Mistake 3: Forgetting the futures gain or loss\nTotal hedged revenue equals spot revenue plus futures gain or loss.\n:::\n\n::: {.callout-warning}\n## Mistake 4: Assuming the hedge locks the exact futures price\nBasis risk means the final effective price may differ from the initial futures price.\n:::\n\n::: {.callout-warning}\n## Mistake 5: Ignoring contract size\nThe number of contracts must be based on the hedged quantity divided by the contract size.\n:::\n\n---\n\n## 15. Practice questions\n\n### Short-answer questions\n\n1. Explain the difference between spot, forward, and futures markets.\n2. Why does a farmer usually use a short futures position for hedging?\n3. What is basis?\n4. Why does basis risk make hedging imperfect?\n5. Why might a farmer prefer partial hedging instead of full hedging?\n\n### Calculation questions\n\n1. A farmer expects to harvest 120 tons of maize. The futures contract size is 10 tons. How many contracts are required for a full hedge?\n\n2. A farmer sells futures at OMR 140 per ton. At harvest, the futures price is OMR 125 per ton. The farmer hedged 80 tons. Calculate the futures gain.\n\n3. A farmer sells 100 tons of barley at a spot price of OMR 90 per ton. The farmer also gains OMR 1,500 from a short futures hedge. Calculate total revenue and effective price.\n\n4. Initial spot price is OMR 118 and initial futures price is OMR 121. At harvest, spot price is OMR 110 and futures price is OMR 113. Calculate the basis at time 0 and at harvest.\n\n5. The correlation between spot and futures price changes is 0.85. The standard deviation of spot price changes is 14 and the standard deviation of futures price changes is 12. Calculate the optimal hedge ratio.\n\n---\n\n## 16. Key takeaways\n\n- Futures markets help farmers and agribusinesses manage price risk.\n- A farmer who will sell output later usually uses a short hedge.\n- Hedged revenue equals spot revenue plus futures gain or loss.\n- Hedging reduces downside price risk but may reduce upside gains.\n- Basis is the difference between spot and futures prices.\n- Basis risk makes futures hedging imperfect.\n- Partial hedging allows the farmer to reduce risk while keeping some exposure to favorable price movements.\n- The optimal hedge ratio depends on the correlation between spot and futures price changes and their relative volatility.\n- In Oman, futures-market logic is especially relevant for imported food commodities, feed costs, and agribusiness risk management.\n\n---\n\n## Source note\n\nThis lecture note is prepared for NREC4230 Agricultural Finance using the course's agricultural finance materials, futures and hedging examples, and agricultural risk-management applications.\n\n",
    "supporting": [
      "lecture-14-futures-hedging-and-basis-risk_files"
    ],
    "filters": [],
    "includes": {}
  }
}