# -*- coding: utf-8 -*-
"""NREC4230_Codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3SsgLvowUQR3_kf2MGlE_vLsi6lXULn

PVIF and FVID Tables
"""

# Import libraries
import pandas as pd
import numpy as np

# Define time periods and interest rates
#time_periods = np.arange(1, 21)  # 1 to 20 years
#interest_rates = np.arange(1, 11) / 100  # 1% to 10%

# Define custom time periods and interest rates
time_periods = [1, 2, 3, 4, 5, 10, 20]  # Custom periods
interest_rates = [0.01, 0.02, 0.03, 0.04, 0.05, 0.10]  # Custom interest rate

# Create PVIF (Present Value Interest Factor) table with rounded values
pvif_table = pd.DataFrame(
    [[round(1 / ((1 + r) ** t), 4) for r in interest_rates] for t in time_periods],
    index=time_periods,
    columns=[f"{int(r*100)}%" for r in interest_rates]
)

# Create FVID (Future Value Interest Discount) table with rounded values
fvid_table = pd.DataFrame(
    [[round((1 + r) ** t, 4) for r in interest_rates] for t in time_periods],
    index=time_periods,
    columns=[f"{int(r*100)}%" for r in interest_rates]
)

print("PVIF Table:")
display(pvif_table)
#print(pvif_table.to_string())  # Ensures proper display of full table

print("\nFVID Table:")
display(fvid_table)
#print(fvid_table.to_string())  # Ensures proper display of full table

"""**Interactive Present Value Plots**"""

import plotly.express as px
import pandas as pd

# Define custom time periods and interest rates
time_periods = [1, 2, 3, 4, 5, 10, 20]  # Custom periods
interest_rates = [0.01, 0.02, 0.03, 0.04, 0.05, 0.10]  # Custom interest rates

# Prepare data for interactive plotting of PVIF (Present Value Interest Factor)
data_pvif = []
for rate in interest_rates:
    for t in time_periods:
        data_pvif.append({"Time (Years)": t, "Present Value": 1 / ((1 + rate) ** t), "Interest Rate": f"{int(rate*100)}%"})

df_pvif = pd.DataFrame(data_pvif)

# Create interactive line plot for PVIF
fig_pvif = px.line(df_pvif, x="Time (Years)", y="Present Value", color="Interest Rate",
                   title="Interactive Present Value of Future Money Over Time for Different Interest Rates",
                   markers=True)

# Show interactive plot
fig_pvif.show()

"""**Interactive Future Value Plots**"""

import plotly.express as px
import pandas as pd

# Prepare data for interactive plotting
data = []
for rate in interest_rates:
    for t in time_periods:
        data.append({"Time (Years)": t, "Future Value": (1 + rate) ** t, "Interest Rate": f"{int(rate*100)}%"})
df = pd.DataFrame(data)

# Create interactive line plot
fig = px.line(df, x="Time (Years)", y="Future Value", color="Interest Rate",
              title="Interactive Growth of Money Over Time for Different Interest Rates",
              markers=True)
# Show interactive plot
fig.show()

"""Here are the **Future Value Interest Factor of Annuity (FVIFA) Table** and **Present Value Interest Factor of Annuity (PVIFA) Table**. These tables show how annuity payments grow over time or how much they are worth in present value."""

# Define time periods and interest rates
time_periods = [1, 2, 3, 4, 5, 10, 20, 30]  # Custom periods
interest_rates = [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.10]  # Custom interest rates

# Create FVIFA (Future Value Interest Factor of Annuity) table
fvifa_table = pd.DataFrame(
    [[round(((1 + r) ** t - 1) / r, 4) if r > 0 else t for r in interest_rates] for t in time_periods],
    index=time_periods,
    columns=[f"{int(r*100)}%" for r in interest_rates]
)

# Create PVIFA (Present Value Interest Factor of Annuity) table
pvifa_table = pd.DataFrame(
    [[round((1 - 1 / ((1 + r) ** t)) / r, 4) if r > 0 else t for r in interest_rates] for t in time_periods],
    index=time_periods,
    columns=[f"{int(r*100)}%" for r in interest_rates]
)

# Display tables
print("Future Value Interest Factor of Annuity (FVIFA) Table:")
print(fvifa_table.to_string())
print("\nPresent Value Interest Factor of Annuity (PVIFA) Table:")
print(pvifa_table.to_string())

"""**Visualize FVIFA and PVIFA**"""

import plotly.express as px
import pandas as pd

# Prepare data for interactive PVIFA plot
data_pvifa = []
for rate in interest_rates:
    for t in time_periods:
        data_pvifa.append({"Time (Years)": t, "PVIFA": (1 - 1 / ((1 + rate) ** t)) / rate, "Interest Rate": f"{int(rate*100)}%"})

df_pvifa = pd.DataFrame(data_pvifa)

# Create interactive line plot for PVIFA
fig_pvifa = px.line(df_pvifa, x="Time (Years)", y="PVIFA", color="Interest Rate",
                    title="Interactive Present Value of Annuity (PVIFA)",
                    markers=True)

# Show interactive PVIFA plot
fig_pvifa.show()

# Prepare data for interactive FVIFA plot
data_fvifa = []
for rate in interest_rates:
    for t in time_periods:
        data_fvifa.append({"Time (Years)": t, "FVIFA": ((1 + rate) ** t - 1) / rate, "Interest Rate": f"{int(rate*100)}%"})

df_fvifa = pd.DataFrame(data_fvifa)

# Create interactive line plot for FVIFA
fig_fvifa = px.line(df_fvifa, x="Time (Years)", y="FVIFA", color="Interest Rate",
                    title="Interactive Future Value of Annuity (FVIFA)",
                    markers=True)

# Show interactive FVIFA plot
fig_fvifa.show()